CREATE DATABASE [PUERTO_RICO_SALARY]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PUERTO_RICO_SALARY', FILENAME = N'H:\sql_data\PUERTO_RICO_SALARY.mdf' , SIZE = 4096KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PUERTO_RICO_SALARY_log', FILENAME = N'E:\Logs\PUERTO_RICO_SALARY_log.ldf' , SIZE = 3072KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET COMPATIBILITY_LEVEL = 110
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET ARITHABORT OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET  READ_WRITE 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET RECOVERY FULL 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET  MULTI_USER 
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PUERTO_RICO_SALARY] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [PUERTO_RICO_SALARY]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [PUERTO_RICO_SALARY] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO


USE [PUERTO_RICO_SALARY]
GO

-- tables
-- Table: "CITY"
CREATE TABLE "CITY" (
    "CITY" char(5)  NOT NULL,
    "DESCRIPTION" text  NOT NULL,
    CONSTRAINT "CITY_pk" PRIMARY KEY  ("CITY")
)
;



-- Table: "EDUCATION"
CREATE TABLE "EDUCATION" (
    "ED_CDE" char(3)  NOT NULL,
    "DESC" text  NOT NULL,
    CONSTRAINT "EDUCATION_pk" PRIMARY KEY  ("ED_CDE")
)
;



-- Table: "POSITION"
CREATE TABLE "POSITION" (
    "POSITION_CDE" char(5)  NOT NULL,
    "DESCRIPTION" text  NOT NULL,
    CONSTRAINT "POSITION_pk" PRIMARY KEY  ("POSITION_CDE")
)
;




-- Table: "SALARY"
CREATE TABLE "SALARY" (
    "POSITION_CDE" char(5)  NOT NULL,
    "ID" int  NOT NULL,
    "DESCRIPTION" text  NOT NULL,
    "SALARY" money  NOT NULL,
    "FREQ_OF_SALARY" int  NOT NULL,
    "CITY" int  NOT NULL,
    "ED_NEEDED" char(3)  NOT NULL,
    "POSITION_POSITION_CDE" char(5)  NOT NULL,
    "CITY_CITY" char(5)  NOT NULL,
    "EDUCATION_ED_CDE" char(3)  NOT NULL,
    CONSTRAINT "SALARY_pk" PRIMARY KEY  ("ID")
)
;




-- foreign keys
-- Reference:  "SALARY_CITY" (table: "SALARY")


ALTER TABLE "SALARY" ADD CONSTRAINT "SALARY_CITY" 
    FOREIGN KEY ("CITY_CITY")
    REFERENCES "CITY" ("CITY")
;

-- Reference:  "SALARY_EDUCATION" (table: "SALARY")


ALTER TABLE "SALARY" ADD CONSTRAINT "SALARY_EDUCATION" 
    FOREIGN KEY ("EDUCATION_ED_CDE")
    REFERENCES "EDUCATION" ("ED_CDE")
;

-- Reference:  "SALARY_POSITION" (table: "SALARY")


ALTER TABLE "SALARY" ADD CONSTRAINT "SALARY_POSITION" 
    FOREIGN KEY ("POSITION_POSITION_CDE")
    REFERENCES "POSITION" ("POSITION_CDE")
;



-- End of file.

